from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path

APP_DIR = Path.home() / ".ytlyrics"
CONFIG_PATH = APP_DIR / "config.json"
TOKEN_PATH = APP_DIR / "token.json"
WORK_DIR = APP_DIR / "work"
OUTPUT_DIR = APP_DIR / "output"
SPRITE_DIR = APP_DIR / "sprites"

BG_PRESETS = ["aurora", "sunset", "ocean", "mono", "violet", "emerald"]


@dataclass
class Config:
    client_id: str = ""
    client_secret: str = ""
    api_video_id: str = ""
    request_command: str = "!lyrics"
    poll_interval: int = 45
    monitor_enabled: bool = True
    default_pitch: float = 0.0
    bg_preset: str = "violet"
    privacy: str = "private"
    upload_enabled: bool = True
    dry_run: bool = False
    title_template: str = "{track} (Lyrics)"
    description_template: str = (
        "{track} lyrics video.\n\n"
        "Auto-generated by YtLyrics.\n"
        "Request via comments: !lyrics Artist - Title\n\n"
        "#lyrics #officiallyrics #{artist_tag}"
    )
    whisper_model: str = "base"
    align_language: str = ""
    resolution: str = "1920x1080"
    fps: int = 30
    scroll_speed: float = 42.0
    font_name: str = "Arial"
    font_size: int = 76
    monitor_poll_count: int = 100

    def ensure_dirs(self) -> None:
        for p in (APP_DIR, WORK_DIR, OUTPUT_DIR, SPRITE_DIR):
            p.mkdir(parents=True, exist_ok=True)


def load_config() -> Config:
    cfg = Config()
    if CONFIG_PATH.exists():
        try:
            data = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            data = {}
        for key, value in data.items():
            if hasattr(cfg, key):
                setattr(cfg, key, value)
    cfg.ensure_dirs()
    return cfg


def save_config(cfg: Config) -> None:
    cfg.ensure_dirs()
    CONFIG_PATH.write_text(
        json.dumps(asdict(cfg), indent=2, ensure_ascii=False), encoding="utf-8"
    )
